trigger: 
  branches:
    include:
      - '*'

jobs:
- template: msbuild-test.yml
  parameters:
    testId: 'msbuilddll'
    testName: 'dotnet ./sdk/8.0.204/MSBuild.dll test'
    testTasks:
      - pwsh: |
          dotnet ./sdk/8.0.204/MSBuild.dll $(Build.SourcesDirectory)/test/maui/maui-test.csproj -getProperty:TargetFrameworks
        displayName: 'getProperty using dotnet ./sdk/8.0.204/MSBuild.dll'
        timeoutInMinutes: 1

- template: msbuild-test.yml
  parameters:
    testId: 'msbuild'
    testName: 'dotnet msbuild test'
    testTasks:
      - pwsh: |
          dotnet msbuild $(Build.SourcesDirectory)/test/maui/maui-test.csproj -getProperty:TargetFrameworks
        displayName: 'getProperty using dotnet msbuild'
        timeoutInMinutes: 1

- template: msbuild-test.yml
  parameters:
    testId: 'build'
    testName: 'dotnet build test'
    testTasks:
      - pwsh: |
          dotnet build $(Build.SourcesDirectory)/test/maui/maui-test.csproj -getProperty:TargetFrameworks
        displayName: 'getProperty using dotnet build'
        timeoutInMinutes: 1
