trigger: 
  branches:
    include:
      - '*'

jobs:
- template: msbuild-test.yml
  parameters:
    testId: 'msbuilddll'
    testName: 'dotnet ./sdk/8.0.204/MSBuild.dll test'
    testCommand: '$env:DOTNET_ROOT/sdk/8.0.204/MSBuild.dll'

- template: msbuild-test.yml
  parameters:
    testId: 'msbuild'
    testName: 'dotnet msbuild test'
    testCommand: 'msbuild'

- template: msbuild-test.yml
  parameters:
    testId: 'build'
    testName: 'dotnet build test'
    testCommand: 'build'
